// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcp42jpStVCNV4Nif9yFGwO1zhsk9XaNs',
    appId: '1:546790936444:web:04afe5e24ae19eb5595ef9',
    messagingSenderId: '546790936444',
    projectId: 'booking-hotel-app-43981',
    authDomain: 'booking-hotel-app-43981.firebaseapp.com',
    storageBucket: 'booking-hotel-app-43981.firebasestorage.app',
    measurementId: 'G-6EVBQNGFTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKTn-mUGSvfJ-Sl2ENGnkiV41zZZJgAcg',
    appId: '1:546790936444:android:08a1d2147184a7e6595ef9',
    messagingSenderId: '546790936444',
    projectId: 'booking-hotel-app-43981',
    storageBucket: 'booking-hotel-app-43981.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtPuvKK4gUVGMWVlZ_QLHD3weFsT9Nuz8',
    appId: '1:546790936444:ios:70fcd1f4644e9b0a595ef9',
    messagingSenderId: '546790936444',
    projectId: 'booking-hotel-app-43981',
    storageBucket: 'booking-hotel-app-43981.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtPuvKK4gUVGMWVlZ_QLHD3weFsT9Nuz8',
    appId: '1:546790936444:ios:70fcd1f4644e9b0a595ef9',
    messagingSenderId: '546790936444',
    projectId: 'booking-hotel-app-43981',
    storageBucket: 'booking-hotel-app-43981.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcp42jpStVCNV4Nif9yFGwO1zhsk9XaNs',
    appId: '1:546790936444:web:e6a98188ced949e9595ef9',
    messagingSenderId: '546790936444',
    projectId: 'booking-hotel-app-43981',
    authDomain: 'booking-hotel-app-43981.firebaseapp.com',
    storageBucket: 'booking-hotel-app-43981.firebasestorage.app',
    measurementId: 'G-JBBWHMYXDL',
  );
}
